# Generated by Django 4.0.6 on 2022-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
